### ISSUE TITLE
The application needs access to valid Yelp API credentials.

### ISSUE THREAD

**Issue by wangsnuxiao** [gcivil-nyu-org/Team_Team6_CS-GY-6063-Fall2021#19]
**User story**
The Django Environment needs access to valid Yelp API credentials.  There should be a variable in Python that holds the value of the API credentials.  We should not hardcode the credentials inside the sourcecode. 

_Suggestion_
We can use ENV variables (eg, using the dotenv package) for local use, and we can use Heroku ENV variables in deployed code

**Acceptance criteria**
1. Django Environment should be able to access valid Yelp API credentials in Heroku
2. Django Environment should be able to access valid Yelp API credentials in local development
3. There should NOT be any hardcoded credentials in source code

**Definition of Done**
1. Acceptance Criteria have been met
2. Code has been reviewed
3. Code has been deployed and works in Heroku environments (integration and production)

**Comment by yp1383** [comment]
The Work is verified in #63
