### ISSUE TITLE
As a Day explorer, I want to search for existing Days

### ISSUE THREAD

**Issue by yp1383** [gcivil-nyu-org/Team_Team6_CS-GY-6063-Fall2021#35]
**User story**
As a Day explorer, I want to search for existing Days.  I can type a search query into the search bar, and see results that match the name of the day.  I can also browse by category

**Acceptance criteria**
1. Search is case insensitive
2. Search returns results for matched name.  Partial matches should be accepted.
3. Browse returns results for any matched Categories (union match).

NOTE: Don't worry about performant queries.  MVP!!

**Definition of Done**

**Comment by sballan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Team6-CS-GY-6063-Fall2021-614a0181a419b90010b164b4/issues/gcivil-nyu-org/Team_Team6_CS-GY-6063-Fall2021/35?planning-poker) with ZenHub @wangsnuxiao @yp1383
